### ISSUE TITLE
模板内需要图片的话路径是什么

### ISSUE THREAD

**Issue by xueqiliu** [BothEyes1993/bes-ui#1]
hello，想问下 模板内需要图片和公共js。 放在哪个文件夹下？路径应该是什么？ 打包后没有src了是吗？

**Comment by BothEyes1993** [comment]
图片静态资源都可以放在static里面，引用的时候用相对路径就可以了，公共js这类的没有什么要求，你自己建立个common文件放就行，然后用的时候自己import就行，至于打包src问题，你可以参考Vue CLI 3.0的库的构建，应用构建一般有src，库的构建是没有的
